# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
# https://github.com/k8s-at-home/charts/blob/master/charts/stable/wireguard/values.yaml
wireguard:
  env:
    TZ: '{{ .Values.global.TZ }}'

  service:
    main:
      type: NodePort
      ports:
        vpn:
          nodePort: 51820
      externalTrafficPolicy: Local
  
  persistence:
    config:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 5Gi
      accessMode: ReadWriteOnce
      retain: true
