# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
image:
  repository: ghcr.io/onedr0p/nzbhydra2
  tag: 4.7.1
  pullPolicy: IfNotPresent

env:
  TZ: '{{ .Values.global.TZ }}'  

controller:
  revisionHistoryLimit: 1

service:
  main:
    ports:
      http:
        port: 5076

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.options: 'nzbhydra2-tlsoption'
    hosts:
    - host: 'hydra.brushfi.re'
      paths:
      - path: /
        pathType: Prefix
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - 'hydra.brushfi.re'

probes:
  liveness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/livenessState
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  readiness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  startup:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 10Gi
    accessMode: ReadWriteOnce
    retain: true

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch
