apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Chart.Name }}.{{ .Values.global.domain }}`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}
          port: http
      middlewares:
        - name: argo-common-crowdsec-traefik-bouncer@kubernetescrd
          namespace: argo-common
  tls:
    secretName: {{ .Chart.Name }}-tls
