apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Chart.Name }}-mqtt
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - mqtt
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}
          port: mqtt
