global:
  repo: https://github.com/jbruns/ArgoCD-SCALE.git
  branch: main
  domain: wavebe.am
  TZ: America/Los_Angeles

  applicationSets:
  - common
  - media

  storage:
    pools: 
    - argo-zfspv-fast: luna-dev/argo/pv
    - argo-zfspv-slow: andromeda-dev/argo/pv

  media:
    uid: 1001
    gid: 1002
    render: 107
    video: 44
    persistentStorageClass: argo-zfspv-fast
    mediaHostPaths: 
    - /mnt/andromeda-dev/media
    nzbgetDownloadsHostPath: /mnt/andromeda-dev/media/nzbdl
