global:
  repo: https://github.com/jbruns/ArgoCD-SCALE.git
  branch: main
  domain: wavebe.am
  TZ: America/Los_Angeles

  applicationSets:
  - common
  - media
  - home
  
  storage:
    pools: 
      argo-zfspv-fast: luna-dev/argo/pv
      argo-zfspv-slow: andromeda-dev/argo/pv
