# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.2.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    # https://github.com/openebs/zfs-localpv/blob/master/docs/backup-restore.md
    - name: openebs-velero-plugin
      image: openebs/velero-plugin:3.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  configuration:
    extraEnvVars:
      TZ: "America/Los_Angeles"
    provider: aws
    backupStorageLocation:
      name: default
      bucket: nobesitiatwa
      prefix: velero
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: http://minio.ix-minio:9000
        publicUrl: https://minio.wavebe.am
    volumeSnapshotLocation:
      name: zfspv-full
      provider: openebs.io/zfspv-blockstore
      config:
        backupPathPrefix: velero
        prefix: zfs
        namespace: openebs
        provider: aws
        region: minio
        s3ForcePathStyle: true
        s3Url: http://minio.ix-minio:9000
        bucket: nobesitiatwa
        # https://github.com/openebs/velero-plugin/pull/55
        multiPartChunkSize: 100Mi
        restApiTimeout: 90s
    resticTimeout: 4h

  credentials:
    existingSecret: velero-s3-key

  schedules:
    daily-backup:
      # backup every day at 0400
      schedule: "0 4 * * *"
      template:
        # expire backups after 1 week
        ttl: "168h"
        excludedNamespaces:
          # skip namespaces managed by TrueNAS SCALE
          - default
          - kube-system
          - kube-public
          - kube-node-lease
          - openebs
          - ix-*
