apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "common.names.fullname" . }}
      rules:
        - alert: ExportarrAbsent
          annotations:
            description: Sonarr Exportarr has disappeared from Prometheus
              service discovery.
            summary: Exportarr is down.
          expr: |
            absent(up{job=~".*{{ include "common.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: SonarrDown
          annotations:
            description: Sonarr service is down.
            summary: Sonarr is down.
          expr: |
            sonarr_system_status{job=~".*{{ include "common.names.fullname" . }}.*"} == 0
          for: 5m
          labels:
            severity: critical
