apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
      rules:
        - alert: ExportarrAbsent
          annotations:
            description: Radarr Exportarr has disappeared from Prometheus
              service discovery.
            summary: Exportarr is down.
          expr: |
            absent(up{job=~".*{{ include "bjw-s.common.lib.chart.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: RadarrDown
          annotations:
            description: Radarr service is down.
            summary: Radarr is down.
          expr: |
            radarr_system_status{job=~".*{{ include "bjw-s.common.lib.chart.names.fullname" . }}.*"} == 0
          for: 5m
          labels:
            severity: critical
