# https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
loki-stack:
  promtail:
    enabled: false
  
  fluent-bit:
    enabled: true
    
    volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /mnt/luna/ix-applications/docker/containers
      - name: ixappsdockercontainers
        hostPath:
          path: /mnt/luna/ix-applications/docker/containers

    volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: ixappsdockercontainers
        mountPath: /mnt/luna/ix-applications/docker/containers
