# https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
loki-stack:

  loki:    
    serviceMonitor:
      enabled: true
      
  promtail:
    enabled: false
  
  fluent-bit:
    enabled: true
    
    serviceMonitor:
      enabled: true
    
    volumes:
      # on SCALE:
      # /var/log/containers ->
      # /var/log/pods
      # Docker containers directory: /mnt/<pool>/ix-applications/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: ixappsdockercontainers
        hostPath:
          path: /mnt/luna/ix-applications/docker/containers

    volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: ixappsdockercontainers
        mountPath: /mnt/luna/ix-applications/docker/containers
