apiVersion: v1
kind: Secret
metadata:
  name: plex-meta-manager-config
  namespace: argo-media
type: Opaque
stringData:
  config.yml: |
    libraries:
      Movies:
      TV Shows:
    plex:
      url: 
      token: 
    tmdb:
      apikey:
      language: en
    tautulli:
      url: 
      apikey: 
    radarr:
      url: 
      token:
      root_folder_path: 
      quality_profile: 
      tag: pmm
    sonarr:
      url: 
      token: 
      root_folder_path: 
      quality_profile: 
      tag: pmm
    trakt:
      client_id: 
      client_secret: 

