apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-critical
spec:
  generators:
    - git:
        repoURL: https://github.com/jbruns/ArgoCD-SCALE.git
        revision: HEAD
        files:
          - path: "cluster-critical/**/gen-config.json"
  template:
    metadata:
      name: '{{ name }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ path }}'
    spec:
      project: cluster-critical
      source:
        path: '{{ path }}'
        targetRevision: HEAD
        repoURL: https://github.com/jbruns/ArgoCD-SCALE.git
        helm:
          valueFiles:
            - values.yaml
            - '{{ valueFile }}'
      destination:
        namespace: '{{ namespace }}'
        name: '{{ cluster }}'
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=orphan
          - CreateNamespace=true
