# https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
# https://github.com/k8s-at-home/charts/blob/master/charts/stable/radarr/values.yaml
radarr:
  image:
    tag: v4.0.4.5922

  env:
    TZ: '{{ .Values.global.TZ }}' 
  
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
        paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: '{{ .Chart.Name }}-tls'
          hosts:
            - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

  persistence:
    config:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/andromeda/media
      mountPath: /media
    nzbdl:
      enabled: true
      type: hostPath
      hostPath: /mnt/andromeda/media/nzbdl
      mountPath: /nzbdl

  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1002
    fsGroup: 1002
    fsGroupChangePolicy: OnRootMismatch

  additionalContainers:
    exportarr:
      name: exportarr
      image: ghcr.io/onedr0p/exportarr:v0.6.2
      imagePullPolicy: IfNotPresent
      args: ["exportarr", "radarr"]
      env:
        - name: URL
          value: "http://localhost:7878"
        - name: PORT
          value: "9793"
        - name: ENABLE_ADDITIONAL_METRICS
          value: "true"
        - name: ENABLE_UNKNOWN_QUEUE_ITEMS
          value: "true"
      
      envFrom:
        - secretRef:
            name: radarr-exportarr-env

      ports:
        - name: metrics
          containerPort: 9793
        
      volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
  
  service:
    metrics:
      enabled: true
      ports:
        metrics:
          enabled: true
          protocol: TCP
          port: 9793