# https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
# https://github.com/k8s-at-home/charts/blob/master/charts/stable/radarr/values.yaml
radarr:
  image:
    tag: v4.0.4.5922

  env:
    TZ: '{{ .Values.global.TZ }}' 
  
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
        paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: '{{ .Chart.Name }}-tls'
          hosts:
            - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

  persistence:
    config:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
    media:
      enabled: true
      type: hostPath
      hostPath: /mnt/andromeda/media
      mountPath: /media
    nzbdl:
      enabled: true
      type: hostPath
      hostPath: /mnt/andromeda/media/nzbdl
      mountPath: /nzbdl

  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1002
    fsGroup: 1002
    fsGroupChangePolicy: OnRootMismatch

metrics:
  enabled: true
  serviceMonitor:
    interval: 3m
    scrapeTimeout: 1m
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []
      # - alert: RadarrDown
      #   annotations:
      #     description: Radarr service is down.
      #     summary: Radarr is down.
      #   expr: |
      #     radarr_system_status == 0
      #   for: 5m
      #   labels:
      #     severity: critical
  exporter:
    image:
      repository: ghcr.io/onedr0p/exportarr
      tag: v1.0.0
      pullPolicy: IfNotPresent
    env:
      port: 9793
      additionalMetrics: false
      unknownQueueItems: false
