# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  logs:
    general:
      level: INFO
    access:
      enabled: true

  # Stops ArgoCD from thinking that ingresses never complete successfully
  # https://github.com/argoproj/argo-cd/issues/968#issuecomment-451082913
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

  ports:
    web:
      redirectTo: websecure

  ingressClass:
    enabled: true
