# https://github.com/k8s-at-home/charts/blob/master/charts/stable/reverse-proxy/values.yaml
reverse-proxy:
  instances:
    - name: home-assistant
      enabled: true
      ip: 172.16.4.61
      port: 8123
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: 'ha.bruns.house'
        paths:
          - path: /
            pathType: Prefix      
        tls:
          - secretName: 'home-assistant-tls'
            hosts:
              - 'ha.bruns.house'

    - name: minio-console
      enabled: true
      ip: 172.16.2.5
      port: 9002
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: 'minio-console.wavebe.am'
        paths:
          - path: /
            pathType: Prefix      
        tls:
          - secretName: 'minio-console-tls'
            hosts:
              - 'minio-console.wavebe.am'

    - name: minio
      enabled: true
      ip: 172.16.2.5
      port: 9000
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: 'minio.wavebe.am'
        paths:
          - path: /
            pathType: Prefix      
        tls:
          - secretName: 'minio-tls'
            hosts:
              - 'minio.wavebe.am'
