# https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml
nextcloud:
  image:
    tag: stable
    
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: nextcloud.bruns.house
      paths:
      - path: /
        pathType: Prefix      
    tls:
      - secretName: nextcloud-tls
        hosts:
          - nextcloud.bruns.house
    
  nextcloud:
    host: nextcloud.bruns.house
    existingSecret:
      enabled: true
      secretName: nextcloud-admin
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    phpConfigs:
      zzz-maximums.ini: |-
        upload_max_filesize=512M
        post_max_size=550M
        memory_limit=1G
  
  externalDatabase:
    enabled: true
    host: "mariadb:3306"
    database: nextclouddb
    existingSecret:
      enabled: true
      secretName: nextcloud-database
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password

  cronjob:
    enabled: true

  persistence:
    enabled: true
    storageClass: argo-zfspv-slow
    size: 4Ti

  metrics:
    enabled: true
    https: true