# https://github.com/k8s-at-home/charts/blob/master/charts/stable/plex/values.yaml
plex:
  env:
    TZ: '{{ .Values.global.TZ }}'
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    PLEX_PREFERENCE_1: "FriendlyName=aMMc"
    PLEX_PREFERENCE_2: "EnableIPv6=0"
    PLEX_PREFERENCE_3: "logDebug=0"
    PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
    PLEX_PREFERENCE_5: "LanNetworksBandwidth=172.16.0.0/16"
    PLEX_PREFERENCE_6: "TranscoderQuality=2"
    PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
    PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

  # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
  service:
    main:
      enabled: true
      type: NodePort
      ports:
        http:
          port: 32400
          protocol: TCP
          nodePort: 32400
      externalTrafficPolicy: Local
    # DLNA UDP: 1900, TCP: 32469
    dlna:
      enabled: true
      type: NodePort
      ports:
        dlna-udp:
          enabled: true
          port: 1900
          protocol: UDP
          nodePort: 1900
        dlna-tcp:
          enabled: true
          port: 32469
          protocol: TCP
          nodePort: 32469
      externalTrafficPolicy: Local
    # Roku/Plex Companion: TCP 8324
    roku:
      enabled: true
      type: NodePort
      ports:
        roku:
          enabled: true
          port: 8324
          protocol: TCP
          nodePort: 8324
      externalTrafficPolicy: Local
    # GDM UDP: 32410, 32412, 32413, 32414
    gdm:
      enabled: true
      type: NodePort
      ports:
        gdm-udp0:
          enabled: true
          port: 32410
          protocol: UDP
          nodePort: 32410
        gdm-udp2:
          enabled: true
          port: 32412
          protocol: UDP
          nodePort: 32412
        gdm-udp3:
          enabled: true
          port: 32413
          protocol: UDP
          nodePort: 32413
        gdm-udp4:
          enabled: true
          port: 32414
          protocol: UDP
          nodePort: 32414
      externalTrafficPolicy: Local

  persistence:
    config:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 100Gi
      accessMode: ReadWriteOnce
      retain: true
    transcode:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 1000Gi
      accessMode: ReadWriteOnce
      retain: true
    data:
      enabled: true
      type: hostPath
      hostPath: /mnt/andromeda-dev/media
      readOnly: true

  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1002
    fsGroup: 1002
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups:
    - 107 # render
    - 44 # video
  
#  resources:
#    limits:
#      nvidia.com/gpu: 1
