# https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
# https://github.com/k8s-at-home/charts/blob/master/charts/stable/mosquitto/values.yaml
mosquitto:
  service:
    main:
      enabled: true
      type: NodePort
      ports:
        mqtt:
          nodePort: 10883
      externalTrafficPolicy: Local
  
  auth:
    enabled: true
  
  persistence:
    data:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 100Mi
      accessMode: ReadWriteOnce
      retain: true
    configinc:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 100Mi
      accessMode: ReadWriteOnce
      retain: true
