# https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/README.md
crowdsec:
  image:
    tag: v1.4.6

  lapi:
    env:
      - name: TZ
        value: '{{ .Values.global.TZ }}'
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-env
            key: ENROLL_KEY
      - name: ENROLL_INSTANCE_NAME
        value: "k3s_cluster_prod"
      - name: ENROLL_TAGS
        value: "k3s linux"

    persistentVolume:
      data:
        storageClassName: argo-zfspv-fast
      config:
        storageClassName: argo-zfspv-fast

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  agent:
    acquisition:
      - namespace: argo-common
        podName: traefik-*
        program: traefik
    
    persistentVolume:
      config:
        enabled: true
      storageClassName: argo-zfspv-fast

    env:
      - name: TZ
        value: '{{ .Values.global.TZ }}'
      - name: PARSERS
        value: "crowdsecurity/cri-logs"
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
