---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  forwardAuth:
    address: http://{{ .Release.Name }}.{{ .Release.Namespace }}/api/v1/forwardAuth
