#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: meisnate12/plex-meta-manager
  tag: v1.15.1
  pullPolicy: IfNotPresent

env:
  # https://github.com/meisnate12/Plex-Meta-Manager/wiki/Run-Commands-&-Environmental-Variables

# No inbound connections are necessary.
service:
  main:
    enabled: false

# Create config volume and mount both the necessary secret to it. This will be copied (via initContainer)
# to the expected location, which will be writable.
persistence:
  config:
    enabled: true
    type: emptyDir
  plex-meta-manager-config:
    enabled: true
    type: secret
    secret:
      secretName: plex-meta-manager-config

lifecycle:
  postStart:
    exec:
      command:
        - /bin/sh
        - -c
        - cp /plex-meta-manager-config/config.yml /config/config.yml

# Configuration file reference: https://github.com/meisnate12/Plex-Meta-Manager/wiki/Configuration-File