# https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
# https://github.com/k8s-at-home/charts/blob/master/charts/stable/home-assistant/values.yaml
home-assistant:
  image:
    tag: stable
    pullPolicy: Always
    
  env:
    TZ: '{{ .Values.global.TZ }}'  
  
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: 'ha.{{ .Values.global.altDomainHome }}'
        paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: '{{ .Chart.Name }}-tls'
          hosts:
            - 'ha.{{ .Values.global.altDomainHome }}'

  persistence:
    config:
      enabled: true
      storageClass: argo-zfspv-fast
      size: 50Gi
      accessMode: ReadWriteOnce
      retain: true

  # http://docs.k8s-at-home.com/our-helm-charts/common-library-add-ons/#code-server
  addons:
    codeserver:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 4.1.0
      workingDir: "/config"
      args:
      - --user-data-dir
      - "/config/.vscode"
      - --extensions-dir
      - "/config/.vscode"
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: 'ha-config.{{ .Values.global.altDomainHome }}'
          paths:
          - path: /
            pathType: Prefix      
        tls:
          - secretName: '{{ .Chart.Name }}-codeserver-tls'
            hosts:
              - 'ha-config.{{ .Values.global.altDomainHome }}'
      volumeMounts:
      - name: config
        mountPath: /config
