apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
spec:
  # Secret names are always required.
  secretName: nzbhydra2-tls
  revisionHistoryLimit: 1
  dnsNames:
    - hydra.brushfi.re
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
